name: Deploy Astro
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: latest

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Pnpm install & build
      run: |
        pnpm install
        pnpm run build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
        name: github-pages
        url: https://tanjilbhuiyan.github.io
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2